on: [push]

name: generate benchmark

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Run benchmark
        run: ./target/release/aoc2021 | tee benchmark.txt
      - name: Commit change
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update benchmark report'
          add: 'benchmark.txt'